// Built-in sound catalog from reference/reference/app/models/sound.rb.
package web

var sounds = map[string]sound{
	"56k":           {Image: "56k.webp", Width: 79, Height: 33},
	"bell":          {Text: "🔔"},
	"bezos":         {Text: "😆💭"},
	"bueller":       {Text: "anyone?"},
	"butts":         {Text: "👐 🚬"},
	"clowntown":     {Image: "clowntown.webp", Width: 210, Height: 150},
	"cottoneyejoe":  {Text: "🎶🙉🎶 "},
	"crickets":      {Text: "hears crickets chirping"},
	"curb":          {Image: "curb.webp", Width: 150, Height: 101},
	"dadgummit":     {Text: "dad gummit!! 🎣"},
	"dangerzone":    {Image: "dangerzone.webp", Width: 157, Height: 32},
	"danielsan":     {Text: "🎆 🏆 🎆"},
	"deeper":        {Image: "top.webp", Width: 188, Height: 80},
	"ballmer":       {Text: "developers!"},
	"donotwant":     {Image: "donotwant.webp", Width: 150, Height: 150},
	"drama":         {Image: "drama.webp", Width: 300, Height: 16},
	"flawless":      {Text: "#flawless"},
	"glados":        {Text: "🤖💢"},
	"gogogo":        {Text: "Go, go, go!"},
	"greatjob":      {Image: "greatjob.webp", Width: 79, Height: 16},
	"greyjoy":       {Text: "😖🎺"},
	"guarantee":     {Text: "guarantees it 👌"},
	"heygirl":       {Text: "✨💁✨"},
	"honk":          {Text: "HONK"},
	"horn":          {Text: "🐶 ✂️ 🐱"},
	"horror":        {Text: "💀 💀 💀 💀 💀 💀 💀"},
	"inconceivable": {Text: "doesn't think it means what you think it means…"},
	"letitgo":       {Text: "❄️👩❄️⛄️❄️"},
	"live":          {Text: "is DOING IT LIVE"},
	"loggins":       {Image: "loggins.webp", Width: 200, Height: 151},
	"makeitso":      {Text: "make it so 👉"},
	"noooo":         {Text: "👸💀😒"},
	"nyan":          {Image: "nyan.webp", Width: 36, Height: 15},
	"ohmy":          {Text: "raises an eyebrow 😏"},
	"ohyeah":        {Text: "isn't playing by the rules"},
	"pushit":        {Image: "pushit.webp", Width: 104, Height: 15},
	"rimshot":       {Text: "plays a rimshot"},
	"rollout":       {Text: "is rolling out 🚗"},
	"rumble":        {Image: "rumble.webp", Width: 220, Height: 150},
	"sax":           {Text: "🌇🎷🎶"},
	"secret":        {Text: "found a secret area 🔑"},
	"sexyback":      {Text: "🔞"},
	"story":         {Text: "and now you know…"},
	"tada":          {Text: "plays a fanfare 🎏"},
	"tmyk":          {Text: "✨ ⭐️ The More You Know ✨ ⭐️"},
	"totes":         {Text: "😁👍"},
	"trololo":       {Text: "трололо"},
	"trombone":      {Text: "plays a sad trombone"},
	"unix":          {Text: "knows this 💻"},
	"vuvuzela":      {Text: "======<() ~ ♪ ~♫"},
	"what":          {Image: "what.webp", Width: 100, Height: 131},
	"whoomp":        {Text: "👏‼️😎"},
	"wups":          {Text: "wups!"},
	"yay":           {Image: "yay.webp", Width: 103, Height: 50},
	"yeah":          {Image: "yeah.webp", Width: 104, Height: 15},
	"yodel":         {Text: "📣🗻🙉"},
}
