// MIME registrations from the pinned reference app.
package integrations

var webhookTypes = map[string][2]string{
	"text/html":                         {"html", "text/html"},
	"application/xhtml+xml":             {"html", "text/html"},
	"text/plain":                        {"text", "text/plain"},
	"text/javascript":                   {"js", "text/javascript"},
	"application/javascript":            {"js", "text/javascript"},
	"application/x-javascript":          {"js", "text/javascript"},
	"text/css":                          {"css", "text/css"},
	"text/calendar":                     {"ics", "text/calendar"},
	"text/csv":                          {"csv", "text/csv"},
	"text/vcard":                        {"vcf", "text/vcard"},
	"text/vtt":                          {"vtt", "text/vtt"},
	"vtt":                               {"vtt", "text/vtt"},
	"text/markdown":                     {"md", "text/markdown"},
	"image/png":                         {"png", "image/png"},
	"image/jpeg":                        {"jpeg", "image/jpeg"},
	"image/gif":                         {"gif", "image/gif"},
	"image/bmp":                         {"bmp", "image/bmp"},
	"image/tiff":                        {"tiff", "image/tiff"},
	"image/svg+xml":                     {"svg", "image/svg+xml"},
	"image/webp":                        {"webp", "image/webp"},
	"video/mpeg":                        {"mpeg", "video/mpeg"},
	"audio/mpeg":                        {"mp3", "audio/mpeg"},
	"audio/ogg":                         {"ogg", "audio/ogg"},
	"audio/aac":                         {"m4a", "audio/aac"},
	"audio/mp4":                         {"m4a", "audio/aac"},
	"video/webm":                        {"webm", "video/webm"},
	"video/mp4":                         {"mp4", "video/mp4"},
	"font/otf":                          {"otf", "font/otf"},
	"font/ttf":                          {"ttf", "font/ttf"},
	"font/woff":                         {"woff", "font/woff"},
	"font/woff2":                        {"woff2", "font/woff2"},
	"application/xml":                   {"xml", "application/xml"},
	"text/xml":                          {"xml", "application/xml"},
	"application/x-xml":                 {"xml", "application/xml"},
	"application/rss+xml":               {"rss", "application/rss+xml"},
	"application/atom+xml":              {"atom", "application/atom+xml"},
	"application/x-yaml":                {"yaml", "application/x-yaml"},
	"text/yaml":                         {"yaml", "application/x-yaml"},
	"multipart/form-data":               {"multipart_form", "multipart/form-data"},
	"application/x-www-form-urlencoded": {"url_encoded_form", "application/x-www-form-urlencoded"},
	"application/json":                  {"json", "application/json"},
	"text/x-json":                       {"json", "application/json"},
	"application/jsonrequest":           {"json", "application/json"},
	"application/problem+json":          {"json", "application/json"},
	"application/pdf":                   {"pdf", "application/pdf"},
	"application/zip":                   {"zip", "application/zip"},
	"application/gzip":                  {"gzip", "application/gzip"},
	"application/x-gzip":                {"gzip", "application/gzip"},
	"text/vnd.turbo-stream.html":        {"turbo_stream", "text/vnd.turbo-stream.html"},
}
