// MIME registration order from Action Dispatch and turbo-rails.
package httpcompat

var mimeTypes = []MIME{
	{"html", "text/html", []string{"application/xhtml+xml"}, []string{"xhtml"}},
	{"text", "text/plain", []string{}, []string{"txt"}},
	{"js", "text/javascript", []string{"application/javascript", "application/x-javascript"}, []string{}},
	{"css", "text/css", []string{}, []string{}},
	{"ics", "text/calendar", []string{}, []string{}},
	{"csv", "text/csv", []string{}, []string{}},
	{"vcf", "text/vcard", []string{}, []string{}},
	{"vtt", "text/vtt", []string{}, []string{"vtt"}},
	{"md", "text/markdown", []string{}, []string{"md", "markdown"}},
	{"png", "image/png", []string{}, []string{"png"}},
	{"jpeg", "image/jpeg", []string{}, []string{"jpg", "jpeg", "jpe", "pjpeg"}},
	{"gif", "image/gif", []string{}, []string{"gif"}},
	{"bmp", "image/bmp", []string{}, []string{"bmp"}},
	{"tiff", "image/tiff", []string{}, []string{"tif", "tiff"}},
	{"svg", "image/svg+xml", []string{}, []string{}},
	{"webp", "image/webp", []string{}, []string{"webp"}},
	{"mpeg", "video/mpeg", []string{}, []string{"mpg", "mpeg", "mpe"}},
	{"mp3", "audio/mpeg", []string{}, []string{"mp1", "mp2", "mp3"}},
	{"ogg", "audio/ogg", []string{}, []string{"oga", "ogg", "spx", "opus"}},
	{"m4a", "audio/aac", []string{"audio/mp4"}, []string{"m4a", "mpg4", "aac"}},
	{"webm", "video/webm", []string{}, []string{"webm"}},
	{"mp4", "video/mp4", []string{}, []string{"mp4", "m4v"}},
	{"otf", "font/otf", []string{}, []string{"otf"}},
	{"ttf", "font/ttf", []string{}, []string{"ttf"}},
	{"woff", "font/woff", []string{}, []string{"woff"}},
	{"woff2", "font/woff2", []string{}, []string{"woff2"}},
	{"xml", "application/xml", []string{"text/xml", "application/x-xml"}, []string{}},
	{"rss", "application/rss+xml", []string{}, []string{}},
	{"atom", "application/atom+xml", []string{}, []string{}},
	{"yaml", "application/x-yaml", []string{"text/yaml"}, []string{"yml", "yaml"}},
	{"multipart_form", "multipart/form-data", []string{}, []string{}},
	{"url_encoded_form", "application/x-www-form-urlencoded", []string{}, []string{}},
	{"json", "application/json", []string{"text/x-json", "application/jsonrequest", "application/problem+json"}, []string{}},
	{"pdf", "application/pdf", []string{}, []string{"pdf"}},
	{"zip", "application/zip", []string{}, []string{"zip"}},
	{"gzip", "application/gzip", []string{"application/x-gzip"}, []string{"gz"}},
	{"turbo_stream", "text/vnd.turbo-stream.html", []string{}, []string{}},
}
